mv AncStateV.c AncStateV.c
mv AncStateV.h AncStateV.h
mv AutoTune.c AutoTune.c
mv AutoTune.h AutoTune.h
mv BatchMode.c BatchMode.c
mv BatchMode.h BatchMode.h
mv BayesModelTest.c BayesModelTest.c
mv BayesTraits.c BayesTraits.c
mv BigLh.c BigLh.c
mv BigLh.h BigLh.h
mv btdebug.c btdebug.c
mv btdebug.h btdebug.h
mv btlapack.c btlapack.c
mv btlapack_dmatrix.c btlapack_dmatrix.c
mv btlapack_dmatrix.h btlapack_dmatrix.h
mv btlapack.h btlapack.h
mv btlapack_interface.c btlapack_interface.c
mv btlapack_interface.h btlapack_interface.h
mv btlin_alg.c btlin_alg.c
mv btlin_alg.h btlin_alg.h
mv btlin_basic.c btlin_basic.c
mv btlin_basic.h btlin_basic.h
mv btlin_dmatrix.c btlin_dmatrix.c
mv btlin_dmatrix.h btlin_dmatrix.h
mv btocl_continuous.c btocl_continuous.c
mv btocl_continuous.h btocl_continuous.h
mv btocl_discrete.c btocl_discrete.c
mv btocl_discrete.h btocl_discrete.h
mv btocl_discrete_lh.c btocl_discrete_lh.c
mv btocl_dmatrix.c btocl_dmatrix.c
mv btocl_dmatrix.h btocl_dmatrix.h
mv btocl_kernels_bayestraits.c btocl_kernels_bayestraits.c
mv btocl_kernels_bayestraits.h btocl_kernels_bayestraits.h
mv btocl_kernels_continuous.h btocl_kernels_continuous.h
mv btocl_kernels_discrete.h btocl_kernels_discrete.h
mv btocl_lin.c btocl_lin.c
mv btocl_lin.h btocl_lin.h
mv btocl_runtime.c btocl_runtime.c
mv btocl_runtime.h btocl_runtime.h
mv btocl_runtime_kernels.c btocl_runtime_kernels.c
mv btocl_runtime_kernels.h btocl_runtime_kernels.h
mv CBlasWrapper.c CBlasWrapper.c
mv CBlasWrapper.h CBlasWrapper.h
mv ckappa.c CKappa.c
mv CKappa.h CKappa.h
mv continuous.c Continuous.c
mv Continuous.h Continuous.h
mv ContrastRegCalcReg.c ContrastRegCalcReg.c
mv ContrastRegCalcReg.h ContrastRegCalcReg.h
mv ContrastRegOutput.c ContrastRegOutput.c
mv ContrastRegOutput.h ContrastRegOutput.h
mv contrasts.c Contrasts.c
mv contrasts.h Contrasts.h
mv contrastsstd.c ContrastsStd.c
mv contrastsstd.h ContrastsStd.h
mv data.c Data.c
mv Data.h Data.h
mv DistData.c DistData.c
mv DistData.h DistData.h
mv FatTail.c FatTail.c
mv FatTail.h FatTail.h
mv Fossil.c Fossil.c
mv Fossil.h Fossil.h
mv gamma.c Gamma.c
mv Gamma.h Gamma.h
mv genlib.c GenLib.c
mv GenLib.h GenLib.h
mv Geo.c Geo.c
mv Geo.h Geo.h
mv GlobalTrend.c GlobalTrend.c
mv GlobalTrend.h GlobalTrend.h
mv initialise.c Initialise.c
mv initialise.h Initialise.h
mv Landscape.c Landscape.c
mv Landscape.h Landscape.h
mv likelihood.c Likelihood.c
mv Likelihood.h Likelihood.h
mv linalg.c LinAlg.c
mv LinAlg.h LinAlg.h
mv LocalTransform.c LocalTransform.c
mv LocalTransform.h LocalTransform.h
mv LocalTransformMLAllNodes.c LocalTransformMLAllNodes.c
mv LocalTransformMLAllNodes.h LocalTransformMLAllNodes.h
mv matrix.c Matrix.c
mv Matrix.h Matrix.h
mv mcmc.c mcmc.c
mv MCMC.h MCMC.h
mv minfit.c MinFit.c
mv MinFit.h MinFit.h
mv ml.c ML.c
mv ML.h ML.h
mv modelfile.c ModelFile.c
mv modelfile.h ModelFile.h
mv NLOptBT.c NLOptBT.c
mv NLOptBT.h NLOptBT.h
mv options.c Options.c
mv Options.h Options.h
mv part.c Part.c
mv part.h Part.h
mv Pattern.c Pattern.c
mv Pattern.h Pattern.h
mv pmatrix.c PMatrix.c
mv pmatrix.h PMatrix.h
mv PMatrixTest.c PMatrixTest.c
mv praxis.c Praxis.c
mv Praxis.h Praxis.h
mv priors.c Priors.c
mv Priors.h Priors.h
mv Prob.c Prob.c
mv Prob.h Prob.h
mv ptrees.c PTrees.c
mv ptrees.h PTrees.h
mv QuadDouble.c QuadDouble.c
mv QuadDouble.h QuadDouble.h
mv randdists.c RandDists.c
mv randdists.h RandDists.h
mv RandLib.c RandLib.c
mv RandLib.h RandLib.h
mv rates.c rates.c
mv Rates.h Rates.h
mv revjump.c RevJump.c
mv RevJump.h RevJump.h
mv RJDummy.c RJDummy.c
mv RJDummy.h RJDummy.h
mv RJLocalScalar.c RJLocalScalar.c
mv RJLocalScalar.h RJLocalScalar.h
mv schedule.c Schedule.c
mv schedule.h Schedule.h
mv SimData.c SimData.c
mv SimData.h SimData.h
mv SliceSampler.c SliceSampler.c
mv SliceSampler.h SliceSampler.h
mv StableDist.c StableDist.c
mv StableDist.h StableDist.h
mv StateSpeciationRate.c StateSpeciationRate.c
mv StateSpeciationRate.h StateSpeciationRate.h
mv StochasticCharacterMapping.c StochasticCharacterMapping.c
mv StochasticCharacterMapping.h StochasticCharacterMapping.h
mv stones.c Stones.c
mv stones.h Stones.h
mv Tag.c Tag.c
mv Tag.h Tag.h
mv threaded.c Threaded.c
mv threaded.h Threaded.h
mv TimeSlices.c TimeSlices.c
mv TimeSlices.h TimeSlices.h
mv TransformTree.c TransformTree.c
mv TransformTree.h TransformTree.h
mv treepasser.c TreePasser.c
mv TreePasser.h TreePasser.h
mv trees.c Trees.c
mv Trees.h Trees.h
mv TypeDef.h TypeDef.h
mv VarRates.c VarRates.c
mv VarRates.h VarRates.h
mv VarRatesMLLocalTransfom.c VarRatesMLLocalTransfom.c
mv VarRatesMLLocalTransfom.h VarRatesMLLocalTransfom.h
