/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class JBayesTraits_JAnalysis */

#ifndef _Included_JBayesTraits_JAnalysis
#define _Included_JBayesTraits_JAnalysis
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JBayesTraits_JAnalysis
 * Method:    RunBayesTraits
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_JBayesTraits_JAnalysis_RunBayesTraits
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
