/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JBayesTraits_JModelRun */

#ifndef _Included_JBayesTraits_JModelRun
#define _Included_JBayesTraits_JModelRun
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JBayesTraits_JModelRun
 * Method:    RunBayesTraits
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_JBayesTraits_JModelRun_RunBayesTraits
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
